# TODO
> PICK UP HERE: **implement model end-to-end ASAP using Dataset, saving model state every N epochs, etc.**
- See todo list in OneNote
- Once working, make the saving model state logic generic so I can use with any model

In [18]:
from datatype_recovery.models.dataset import TypeSequenceDataset

data_params = {
    'experiment_runs': [
        '/home/cls0027/test_builds/astera.exp/rundata/run1',
        '/home/cls0027/test_builds/coreutils.exp/rundata/run1',
    ],
    'copy_data': False,
}
dataset = TypeSequenceDataset('model0_dataset', data_params, max_hops=3)

input_params will be IGNORED in favor of saved .json file (model0_dataset/raw/input_params.json)


In [155]:
# TODO: split test/train on BINARY boundary to prevent functions/vars from crossing
# -> I have varid tuples, so I can get (rungid, binid) from that and use it to split
#   - extract (idx, rungid, binid) for each data point and put into a dataframe
#   - groupby/count dataframe by (rungid/binid) and come up with split that is close to target %
#   - collect indices for each data point within each subset (test/train/valid)
#   - quick/simple validate that all (rungid/binid) combos are unique to a subset
#
# [(i, x.varid[0], x.varid[1]) for i, x in enumerate(dataset[10000:10100])][:5]

from torch_geometric.loader import DataLoader
from torch.utils.data import Subset

# tiny subset to start
trainset_indices = list(range(12))
testset_indices = list(range(100,112))

train_set = Subset(dataset, trainset_indices)
test_set = Subset(dataset, testset_indices)

# TODO: we probably will need to ensure the dataset is a multiple of the chosen batch size
# (maybe drop the last len(dataset)%BATCH_SIZE samples)
BATCH_SIZE = 4

train_loader = DataLoader(train_set, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_set, batch_size=BATCH_SIZE, shuffle=True)

# EXAMPLE: the shuffled slice changes each time, but dataset[0] stays consistent
# print(dataset[:10].shuffle()[0].varid)
# print(dataset[0].varid)

In [167]:
for step, data in enumerate(train_loader):
    print(f'Step {step+1}')
    print(f'Num graphs in batch: {data.num_graphs}')
    print(data)
    print(data.batch)
    print()

Step 1
Num graphs in batch: 4
DataBatch(x=[59, 47], edge_index=[2, 112], y=[4, 20], varid=[4], batch=[59], ptr=[5])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

Step 2
Num graphs in batch: 4
DataBatch(x=[53, 47], edge_index=[2, 106], y=[4, 20], varid=[4], batch=[53], ptr=[5])
tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3])

Step 3
Num graphs in batch: 4
DataBatch(x=[88, 47], edge_index=[2, 170], y=[4, 20], varid=[4], batch=[88], ptr=[5])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,
        3, 3, 3, 3, 3, 3

In [186]:
loader1 = DataLoader(train_set, batch_size=4)
list(loader1)

[DataBatch(x=[76, 47], edge_index=[2, 144], y=[4, 20], varid=[4], batch=[76], ptr=[5]),
 DataBatch(x=[66, 47], edge_index=[2, 126], y=[4, 20], varid=[4], batch=[66], ptr=[5]),
 DataBatch(x=[58, 47], edge_index=[2, 118], y=[4, 20], varid=[4], batch=[58], ptr=[5])]

In [189]:
loader2 = DataLoader(train_set, batch_size=1)
list(loader2)

[DataBatch(x=[11, 47], edge_index=[2, 20], y=[1, 20], varid=[1], batch=[11], ptr=[2]),
 DataBatch(x=[21, 47], edge_index=[2, 40], y=[1, 20], varid=[1], batch=[21], ptr=[2]),
 DataBatch(x=[17, 47], edge_index=[2, 32], y=[1, 20], varid=[1], batch=[17], ptr=[2]),
 DataBatch(x=[27, 47], edge_index=[2, 52], y=[1, 20], varid=[1], batch=[27], ptr=[2]),
 DataBatch(x=[14, 47], edge_index=[2, 26], y=[1, 20], varid=[1], batch=[14], ptr=[2]),
 DataBatch(x=[19, 47], edge_index=[2, 36], y=[1, 20], varid=[1], batch=[19], ptr=[2]),
 DataBatch(x=[23, 47], edge_index=[2, 46], y=[1, 20], varid=[1], batch=[23], ptr=[2]),
 DataBatch(x=[10, 47], edge_index=[2, 18], y=[1, 20], varid=[1], batch=[10], ptr=[2]),
 DataBatch(x=[5, 47], edge_index=[2, 16], y=[1, 20], varid=[1], batch=[5], ptr=[2]),
 DataBatch(x=[34, 47], edge_index=[2, 66], y=[1, 20], varid=[1], batch=[34], ptr=[2]),
 DataBatch(x=[6, 47], edge_index=[2, 10], y=[1, 20], varid=[1], batch=[6], ptr=[2]),
 DataBatch(x=[13, 47], edge_index=[2, 26], y=[1

In [197]:
list(loader2)[0].x.shape
for x in loader2:
    print(x.x.shape)

torch.Size([11, 47])
torch.Size([21, 47])
torch.Size([17, 47])
torch.Size([27, 47])
torch.Size([14, 47])
torch.Size([19, 47])
torch.Size([23, 47])
torch.Size([10, 47])
torch.Size([5, 47])
torch.Size([34, 47])
torch.Size([6, 47])
torch.Size([13, 47])


In [356]:
print('Batch')
for x in loader1:
    print(x.x.shape, x.edge_index.shape)

print('Non batch')
for x in loader2:
    print(x.x.shape, x.edge_index.shape)

Batch
torch.Size([76, 47]) torch.Size([2, 144])
torch.Size([66, 47]) torch.Size([2, 126])
torch.Size([58, 47]) torch.Size([2, 118])
Non batch
torch.Size([11, 47]) torch.Size([2, 20])
torch.Size([21, 47]) torch.Size([2, 40])
torch.Size([17, 47]) torch.Size([2, 32])
torch.Size([27, 47]) torch.Size([2, 52])
torch.Size([14, 47]) torch.Size([2, 26])
torch.Size([19, 47]) torch.Size([2, 36])
torch.Size([23, 47]) torch.Size([2, 46])
torch.Size([10, 47]) torch.Size([2, 18])
torch.Size([5, 47]) torch.Size([2, 16])
torch.Size([34, 47]) torch.Size([2, 66])
torch.Size([6, 47]) torch.Size([2, 10])
torch.Size([13, 47]) torch.Size([2, 26])


In [260]:
b = list(loader1)[0]
print(f'b.x shape: {b.x.shape}')
print(f'b.batch shape: {b.batch.shape}')

for i in range(4):
    print(i, len(b.batch[b.batch == i]))

# TODO: need to verify I am collecting node 0 properly from each batch
# - node 0 will always be a DeclRefExpr
# - the model output prediction and ground truth y tensor for each sample
#   corresponds to making a prediction on NODE 0
# - I should be able to check this against a "non-batched" (and non-shuffled) data
#   loader and make sure I get all the same answers

b.x[0]
(b.x[11]==b.x[0]).all()

from datatype_recovery.models.dataset.encoding import decode_astnode

print(decode_astnode(b.x[0]))
print(decode_astnode(b.x[0+11]))
print(decode_astnode(b.x[0+11+21]))
print(decode_astnode(b.x[0+11+21+17]))

b.x shape: torch.Size([76, 47])
b.batch shape: torch.Size([76])
0 11
1 21
2 17
3 27
DeclRefExpr
DeclRefExpr
DeclRefExpr
DeclRefExpr


In [340]:
print(0)
print(0+11)
print(0+11+21)
print(0+11+21+17)
print()
print(11+21+17+27)

0
11
32
49

76


In [302]:
node0_idx = (b.batch==3).nonzero(as_tuple=True)[0][0].item()
node0_idx

49

In [308]:
decode_astnode(b.x[node0_idx])

'DeclRefExpr'

# Handle Batches
This code 

In [396]:
# or more elegantly...

# def get_batch_
batch_graphs = [(b.batch==i).nonzero(as_tuple=True) for i in range(BATCH_SIZE)]

node0_indices = [x[0][0].item() for x in batch_graphs]
node0_indices
batch_graphs
# batch shape: [76, 47]
# - 76 = sum of nodes in all graphs within the batch = 11+21+17+27
# - 47 = # node features
batch_graphs
# list of tensors, one tensor per graph within the batch
# --> list of node_indexes, one per graph within the batch
# each tensor holds a list of node indices for the nodes of that graph
# (the indices index into b.x)
# indices of nodes

import torch
from torch_geometric.data.batch import DataBatch
from typing import List

def split_node_index_by_graph(data_batch:DataBatch, batch_size:int) -> List[torch.tensor]:
    '''
    Returns the node_index for each individual graph within the batch as a list of tensors.

    Each list entry (node_index) is a tensor of node indices for an individual graph within the
    batch, where each of the node indices will index into data_batch.x.
    '''
    return [(data_batch.batch==i).nonzero(as_tuple=True) for i in range(batch_size)]

batch_graphs
b.edge_index.shape

# c = list(loader2)[:4]
for x in list(loader2)[:4]:
    print(x)

# len(b.batch)
# list(loader2)[3].edge_index
# b.edge_index
# b.batch[(b.batch==0).nonzero(as_tuple=True)]



# ------------------------
# TODO: ok, here is the way to get node 0 indices
# - edge_index should be able to take care of itself - we just pass it through, I
#   don't think we need to do anything to it (it's correct, but won't have edges
#   going between independent graphs of course)
# ------------------------
# TODO: PICK UP HERE and IMPLEMENT THE MODEL!!!
# ------------------------
# - use node0_indices to pull target node embeddings, passing into final layer (linear for now?)
# - return prediction...finish building training function
# - INTEGRATE WANDB!!
# ------------------------
node_index_by_graph = split_node_index_by_graph(b, BATCH_SIZE)
node0_indices = [x[0][0].item() for x in node_index_by_graph]
node0_indices

DataBatch(x=[11, 47], edge_index=[2, 20], y=[1, 20], varid=[1], batch=[11], ptr=[2])
DataBatch(x=[21, 47], edge_index=[2, 40], y=[1, 20], varid=[1], batch=[21], ptr=[2])
DataBatch(x=[17, 47], edge_index=[2, 32], y=[1, 20], varid=[1], batch=[17], ptr=[2])
DataBatch(x=[27, 47], edge_index=[2, 52], y=[1, 20], varid=[1], batch=[27], ptr=[2])


[0, 11, 32, 49]

In [334]:
(b.x[node0_indices] == b.x[:4]).all()



tensor(False)

In [264]:
for i in range(b.x.shape[0]):
    print(decode_astnode(b.x[i]))

DeclRefExpr
BinaryOperator
CallExpr
DeclRefExpr
DeclRefExpr
BinaryOperator
ParenExpr
CStyleCastExpr
IntegerLiteral
CallExpr
DeclRefExpr
DeclRefExpr
BinaryOperator
CallExpr
DeclRefExpr
DeclRefExpr
StringLiteral
BinaryOperator
CallExpr
DeclRefExpr
DeclRefExpr
StringLiteral
BinaryOperator
IntegerLiteral
BinaryOperator
CallExpr
DeclRefExpr
DeclRefExpr
StringLiteral
CallExpr
DeclRefExpr
DeclRefExpr
DeclRefExpr
BinaryOperator
IntegerLiteral
BinaryOperator
BinaryOperator
ParenExpr
DeclRefExpr
CallExpr
BinaryOperator
DeclRefExpr
DeclRefExpr
DeclRefExpr
UnaryOperator
CStyleCastExpr
UnaryOperator
CStyleCastExpr
DeclRefExpr
DeclRefExpr
BinaryOperator
IntegerLiteral
BinaryOperator
IntegerLiteral
BinaryOperator
IntegerLiteral
BinaryOperator
IntegerLiteral
BinaryOperator
IntegerLiteral
BinaryOperator
IntegerLiteral
BinaryOperator
IntegerLiteral
CallExpr
DeclRefExpr
IntegerLiteral
UnaryOperator
DeclRefExpr
UnaryOperator
DeclRefExpr
IntegerLiteral
IntegerLiteral
IntegerLiteral
IntegerLiteral
IntegerLi

In [201]:
print('Batch')
for x in loader1:
    print(x.y.shape)

print('Non batch')
for x in loader2:
    print(x.y.shape)

Batch
torch.Size([4, 20])
torch.Size([4, 20])
torch.Size([4, 20])
Non batch
torch.Size([1, 20])
torch.Size([1, 20])
torch.Size([1, 20])
torch.Size([1, 20])
torch.Size([1, 20])
torch.Size([1, 20])
torch.Size([1, 20])
torch.Size([1, 20])
torch.Size([1, 20])
torch.Size([1, 20])
torch.Size([1, 20])
torch.Size([1, 20])


In [166]:
import torch
from torch_geometric.data import Dataset
from torch_geometric.nn import GATConv

class TypeSeqModel(torch.nn.Module):
    def __init__(self, dataset:Dataset, hidden_channels:int):
        super(TypeSeqModel, self).__init__()

        self.gat1 = GATConv(dataset.num_node_features, hidden_channels)
        self.gat2 = GATConv(hidden_channels, hidden_channels)

    def forward(self, x, edge_index, batch)

tensor([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# TODO: training

torch.manual_seed(33)

In [31]:


# TEMP: just split randomly for now
len(dataset)

44021

In [100]:
rungid, bid, _, _, _ = dataset[0].varid
[(x.varid[0], x.varid[1]) for x in dataset[10000:10100]][:5]

[(1, 81.0), (1, 81.0), (1, 81.0), (1, 81.0), (1, 82.0)]

In [107]:
[(i, x.varid[0], x.varid[1]) for i, x in enumerate(dataset[10000:10100])][:5]

indices = [10000, 10001, 10002, 10003, 10004]
from torch.utils.data import Subset

ss = Subset(dataset, indices)

In [137]:
# [(x.varid[0], x.varid[1]) for x in ss.shuffle()]
loader = DataLoader(ss, shuffle=True)

In [138]:
[(x.varid[0][0], x.varid[0][1]) for x in loader]

[(1, 81.0), (1, 82.0), (1, 81.0), (1, 81.0), (1, 81.0)]

In [164]:
from pathlib import Path
import pandas as pd
pd.read_csv(Path('/home/cls0027/test_builds/coreutils.exp/rundata/run1/binaries.csv')).BinaryId
df = pd.read_csv(Path('/home/cls0027/test_builds/coreutils.exp/rundata/run1/locals.csv'))
# df.BinaryId = df.BinaryId.astype('int64')
# df.loc[:,'NEW_COL'] = pd.Series([1e3]*len(df), dtype='int64')
df.BinaryId

0          0
1          0
2          0
3          0
4          0
        ... 
11580    116
11581    116
11582    116
11583    116
11584    116
Name: BinaryId, Length: 11585, dtype: int64

In [83]:
df.NEW_COL

0        1000
1        1000
2        1000
3        1000
4        1000
         ... 
11580    1000
11581    1000
11582    1000
11583    1000
11584    1000
Name: NEW_COL, Length: 11585, dtype: int64

In [86]:
df = pd.read_csv(Path('/home/cls0027/test_builds/coreutils.exp/rundata/run1/47.pathchk/functions.csv'))
df.BinaryId

0      47
1      47
2      47
3      47
4      47
       ..
101    47
102    47
103    47
104    47
105    47
Name: BinaryId, Length: 106, dtype: int64